import uuid as _uuid
from datetime import datetime, date

from sqlalchemy import String, Boolean, DateTime, Date, Float, ForeignKey, Integer, SmallInteger, text
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base
from app.utils.datetime_helper import get_current_time


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    # Surrogate UUID for cross-system references; generated by Postgres
    # via `gen_random_uuid()` so INSERTs without an explicit value still
    # populate the column.
    uuid: Mapped[_uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        unique=True,
        nullable=False,
        server_default=text("gen_random_uuid()"),
    )
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    full_name: Mapped[str] = mapped_column(String(100))
    date_of_birth: Mapped[date | None] = mapped_column(Date, nullable=True)
    phone: Mapped[str | None] = mapped_column(String(20), nullable=True)
    role: Mapped[str] = mapped_column(String(20), default="user")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    is_verified: Mapped[bool] = mapped_column(Boolean, default=False)
    avatar_url: Mapped[str | None] = mapped_column(nullable=True)
    # Medical information fields
    gender: Mapped[str | None] = mapped_column(String(10), nullable=True)
    blood_type: Mapped[str | None] = mapped_column(String(5), nullable=True)
    # DB column is `smallint`; storing floats here previously caused silent
    # rounding (175.5 -> 176). Match the column type exactly so the loss
    # surfaces at the validation layer instead.
    height_cm: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    weight_kg: Mapped[float | None] = mapped_column(Float, nullable=True)
    medications: Mapped[list[str]] = mapped_column(ARRAY(String), default=list, server_default="{}")
    allergies: Mapped[list[str]] = mapped_column(ARRAY(String), default=list, server_default="{}")
    medical_conditions: Mapped[list[str]] = mapped_column(ARRAY(String), default=list, server_default="{}")
    # Localization (DB columns have server defaults; mirror them here so a
    # row constructed via `User(...)` without explicit values still ends
    # up with the same canonical strings the DB would have inserted).
    language: Mapped[str | None] = mapped_column(
        String(10), nullable=True, server_default="vi"
    )
    timezone: Mapped[str | None] = mapped_column(
        String(50), nullable=True, server_default="Asia/Ho_Chi_Minh"
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=get_current_time)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=get_current_time, onupdate=get_current_time)
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # --- Authentication state (auth-internal; not exposed via the
    #     mobile profile API on purpose). Previously these columns
    #     existed in the DB without being declared on the model, so any
    #     code path using `db.refresh(user)` and then reading e.g.
    #     `user.token_version` would have raised AttributeError.
    token_version: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="1"
    )
    failed_login_attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    locked_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # --- Email verification (6-digit PIN code) ---
    # Stored as VARCHAR(6) to preserve leading zeros (e.g. '012345'). NULL after verified.
    verification_code: Mapped[str | None] = mapped_column(String(6), nullable=True)
    verification_code_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # --- Password reset (6-digit PIN code) ---
    # NULL after reset is used. Expires in 15 minutes.
    reset_code: Mapped[str | None] = mapped_column(String(6), nullable=True)
    reset_code_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # --- Phase 3: Primary device pointer ---
    # The single device whose readings drive the dashboard / latest-vitals
    # tile for this user. Multi-device ownership stays first-class
    # (vitals.device_id is unchanged), but UI surfaces filter on this
    # pointer so users always see one canonical "current source" instead
    # of the racy latest-of-all behaviour. ON DELETE SET NULL keeps the
    # user row alive when the picked device is unbound.
    primary_device_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("devices.id", ondelete="SET NULL"),
        nullable=True,
    )

